name: Spark Encoders

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false # Set to false so one failing job doesn't cancel the other
      matrix:
        include:
          - os: ubuntu-22.04
            java: 8
            spark: 3.3.4
          - os: ubuntu-22.04
            java: 8
            spark: 3.4.4
          - os: ubuntu-22.04
            java: 8
            spark: 3.5.7
          - os: ubuntu-22.04
            java: 17
            spark: 4.0.1
    runs-on: ${{ matrix.os }}
    env:
      SPARK_VERSION: ${{ matrix.spark }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache SBT deps
        uses: coursier/cache-action@v6
      - name: Setup Scala with SBT
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{ matrix.java }}
          apps: sbt
      - name: Test
        run: sbt -v "+ test"