name: Release
on:
  push:
    branches: [main]
    tags: ["**"]
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        java: [ 8 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache SBT deps
        uses: coursier/cache-action@v6
      - name: Setup Scala with SBT
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{ matrix.java }}
          apps: sbt
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
